# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS-LY' do
pod 'Masonry','~> 1.0.2'
pod 'AFNetworking','~> 3.1.0'
pod 'DCScrollView','~> 1.2.0'
pod 'SVProgressHUD','~> 2.1.2'
#pod 'FMDB','~> 2.6.2'
pod 'SDWebImage','~> 4.0.0'
pod 'MagicalRecord','~> 2.3.2’
pod 'MBProgressHUD','~> 1.0.0'
pod 'IQKeyboardManager','~> 4.0.8'
pod 'SVProgressHUD','~> 2.1.2'
pod 'RealReachability', '~> 1.1.8'
pod 'YYKit', '~> 1.0.9'

end
